Add optional input param encode_binary_format and change cbor.to_jsonb() to expect one CBOR item
A new function, cbor.to_jsonb_array(), has been added to support what
seems to be the special case of having multiple CBOR items on the root level.

If multiple CBOR items are encoutered by cbor.to_jsonb(),
it will now throw this error:

   ERROR: Multiple root level CBOR items. Use to_jsonb_array() instead if this is expected.

The new input parameter encode_binary_format can be used to control
how binary strings are encoded. The default is 'hex'.
Supports the same formats as the PostgreSQL built-in encode(),
such as also 'base64'.