Specify type for ROW() explicitly needed for PostgreSQL 12 compatibility
This fixes the below problem reported by Rickard Carlswärd:

postgres=# SELECT cbor.to_jsonb('\xa26161016162820203'::bytea);
ERROR:  return type mismatch in function declared to return cbor.next_state
DETAIL:  Final statement returns record instead of bytea at column 1.
CONTEXT:  SQL function "next_map" during startup
SQL function "next_item" statement 1
SQL function "to_jsonb" statement 1